global using Faluf.Trading.Core.Abstractions.Interfaces;
global using Faluf.Trading.Core.Abstractions.Models;
global using Faluf.Trading.Core.Domain;
global using Faluf.Trading.Core.DTOs.Inputs;
global using Faluf.Trading.Core.DTOs.Outputs;
global using Faluf.Trading.Core.Enums;
global using Faluf.Trading.Core.Filters;
global using FluentValidation;
global using Microsoft.Extensions.Localization;
